### ISSUE TITLE
--oui_update does not update local manuf db

### ISSUE THREAD

**Issue by joshschmelzle** [WLAN-Pi/wlanpi-profiler#13]
```
wlanpi@wlanpi-dev:~$ sudo profiler --oui_update
2020-05-29 23:06:31,700 [INFO] start: profiler2 version 0.0.1.dev3
2020-05-29 23:06:31,701 [INFO] start: python platform version is 3.7.6
2020-05-29 23:06:33,579 [ERROR] update_manuf: problem updating manuf. make sure manuf-ng is installed...
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/profiler2/helpers.py", line 390, in update_manuf
    ["sudo", "manuf", "--update"], shell=False, check=True, capture_output=True
  File "/usr/local/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['sudo', 'manuf', '--update']' returned non-zero exit status 1.
exiting...
wlanpi@wlanpi-dev:~$ sudo manuf --update
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/manuf/manuf.py", line 142, in update
    response = urlopen(manuf_url)
  File "/usr/local/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/local/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/lib/python3.7/urllib/request.py", line 563, in error
    result = self._call_chain(*args)
  File "/usr/local/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.7/urllib/request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/local/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/local/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/local/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/manuf", line 11, in <module>
    load_entry_point('manuf-ng==1.0.0', 'console_scripts', 'manuf')()
  File "/usr/local/lib/python3.7/site-packages/manuf/manuf.py", line 319, in main
    parser = MacParser(manuf_name=args.manuf, update=args.update)
  File "/usr/local/lib/python3.7/site-packages/manuf/manuf.py", line 68, in __init__
    self.update()
  File "/usr/local/lib/python3.7/site-packages/manuf/manuf.py", line 144, in update
    raise URLError("Failed downloading OUI database")
urllib.error.URLError: <urlopen error Failed downloading OUI database>
```

**Comment by joshschmelzle** [comment]
fixed in ae71ccb12f1340ecaee421f28fa8ca1efd544b15 by @kmillerusaf 
confirmed in dev branch:
```
wlanpi@wlanpi:/opt/wlanpi/profiler2$ sudo profiler --oui_update --logging debug
2020-06-15 01:33:41,890 [INFO] start: profiler2 version 0.1.dev7
2020-06-15 01:33:41,890 [INFO] start: python platform version is 3.7.3
2020-06-15 01:33:41,891 [DEBUG] start: args: Namespace(channel=None, clean=False, config='/usr/local/lib/python3.7/dist-packages/profiler2/config.ini', files_root='/var/www/html', ft_enabled=True, he_enabled=True, hostname_as_ssid=False, interface=None, listen_only=False, logging='debug', menu_file='/tmp/profiler_menu_report.txt', menu_mode=False, oui_update=True, pcap_analysis_only=None, ssid=None)
2020-06-15 01:33:41,893 [DEBUG] update_manuf: manuf flat file located at /usr/local/lib/python3.7/dist-packages/manuf/manuf
2020-06-15 01:33:41,894 [DEBUG] update_manuf: manuf last modified time: Thu Jun 11 17:22:37 2020
2020-06-15 01:33:41,894 [DEBUG] update_manuf: running 'sudo manuf --update'
2020-06-15 01:33:47,428 [DEBUG] update_manuf: manuf last modified time: Mon Jun 15 01:33:45 2020
```
