### ISSUE TITLE
python platform version TypeError

### ISSUE THREAD

**Issue by joshschmelzle** [WLAN-Pi/wlanpi-profiler#3]
Running profiler2 version 0.0.1.dev1 on my Python3.7.6 build I get the following TypeError when the program is first launched. It seems to only be cosmetic. 

```
sudo python3.7 -m profiler2 -c 11 --logging debug --no11ax --no11r
2020-04-25 22:32:13,078 [INFO] start: profiler2 version 0.0.1.dev1
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/logging/__init__.py", line 1025, in emit
    msg = self.format(record)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 869, in format
    return fmt.format(record)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 608, in format
    record.message = record.getMessage()
  File "/usr/local/lib/python3.7/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/wlanpi/profiler2/profiler2/__main__.py", line 55, in <module>
    main()
  File "/home/wlanpi/profiler2/profiler2/__main__.py", line 50, in main
    manager.start(args)
  File "/home/wlanpi/profiler2/profiler2/manager.py", line 52, in start
    log.info("python platform version is", platform.python_version())
Message: 'python platform version is'
Arguments: ('3.7.6',)
```

WLAN Pi build information:

- WLAN Pi v1.9
- Linux wlanpi-dev 4.19.66-sunxi64 #5.93.190815 SMP Thu Aug 15 23:19:53 CEST 2019 aarch64 GNU/Linux
- Debian GNU/Linux 9.12 (stretch)

**Comment by joshschmelzle** [comment]
fixed formatting error
